export default Object.freeze({
  CANVAS_WIDTH: 360,
  CANVAS_HEIGHT: 400,
  CANVAS_REAL_WIDTH_MIN: 0,
  CANVAS_REAL_HEIGHT_MIN: 0,
  CANVAS_REAL_WIDTH_MAX: 290,
  CANVAS_REAL_HEIGHT_MAX: 145,

  SNAKE_BODY_WIDTH_UNIT: 10,
  SNAKE_BODY_HEIGHT_UNIT: 5,
  FRAME_DOWN_UNIT: 1,
  FRAME_DOWN_LIMIT: 30,
  TICK_TOC_UNIT: 10,

  SNAKE_BODY_COLOR: '#f5046d',
  FOOD_COLOR: '#676FA3',

  SNAKE_LEFT_DIRECTION: 'LEFT',
  SNAKE_RIGHT_DIRECTION: 'RIGHT',
  SNAKE_UP_DIRECTION: 'UP',
  SNAKE_DOWN_DIRECTION: 'DOWN',
  SNAKE_STOP: 'STOP',
});
